### ISSUE TITLE
LICENSE clarification

### ISSUE THREAD

**Issue by FabioPinheiro** [roots-id/didcomm-mediator#14]
Hey Rodolfo,
Would be possible to define a license for this repository?

We wanted to use this DID Comm mediator to test interoperability with our agents (clients), that we are developing.
I am wondering if you could clarify and add a LICENSE file.

Thank you in advance for any information you can provide

**Comment by 2byrds** [comment]
Hi Fabio, Thank you for reaching out! I have added a LICENSE file to main, it is Apache 2.0

**Comment by FabioPinheiro** [comment]
That is great!
Thanks a lot for the rapid response.
