### ISSUE TITLE
In the Mediate Grant message should the routing_did be an array?

### ISSUE THREAD

**Issue by FabioPinheiro** [roots-id/didcomm-mediator#17]
The example of the Mediate Grant message in https://didcomm.org/mediator-coordination/2.0/ seems to not be correct.

In the body of the `"https://didcomm.org/coordinate-mediation/2.0/mediate-grant"` the field `routing_did` is an array.

```
...
"routing_did": ["did:peer:z6Mkfriq1MqLBoPWecGoDLjguo1sB9brj6wT3qZ5BxkKpuP6"]
```

but on this mediator, the reply is just a string

```
{
  "id" : "bafa9e69-5ce0-411c-89eb-eb4bade6949d",
  "typ" : "application/didcomm-plain+json",
  "type" : "https://didcomm.org/coordinate-mediation/2.0/mediate-grant",
  "body" : {
    "routing_did" : "did:peer:2.Ez6LSoUkkHrYaDgGUdF6Vs6NnNyjahQmLKGsHhuZRy92qL1y4.Vz6MknogVLc4883Gys8GjzGZWnu4R1RjiCLDDrDxb7ToaDUeU.SeyJpZCI6Im5ldy1pZCIsInQiOiJkbSIsInMiOiJodHRwOi8vcm9vdHNpZC1tZWRpYXRvcjo4MDAwIiwiYSI6WyJkaWRjb21tL3YyIl19"
  }
}
```

**Comment by rodolfomiranda** [comment]
You are right. However the error is on the spec. There is a pending PR to fix that in the spec: https://github.com/decentralized-identity/didcomm.org/pull/59
Thanks for the catch!

**Comment by FabioPinheiro** [comment]
Thanks for the clarification
Let's close this issue then.
