### ISSUE TITLE
Pickup-Protocol 3.0 recipient_key was renamed

### ISSUE THREAD

**Issue by bsandmann** [roots-id/didcomm-mediator#19]
According to the description of the  [Picktup 3.0 protocol](https://didcomm.org/pickup/3.0/), a selector called "recipient_did" can be used to query messages for that specific did.

In the current codebase "recipient_key" is used everywhere, which seems to be a relic of the 2.0 version of the same protocol.
eg.
`
        body={
                "recipient_key": recipient_key,
...
}`

Currently this causes a problem when trying to select specific messages.

**Comment by rodolfomiranda** [comment]
Thanks @bsandmann . You are right. The code was not updated to the new protocol changes yet. For the moment please try not to use the recipient_key filter until we push a fix. I'll let you know in this issue.

**Comment by rodolfomiranda** [comment]
We upload a new version that handles both `recipient_key` and `recipient_did`
